import Link from "next/link"

export const metadata = { title: "Privacy Policy" }

export default function PrivacyPage() {
  return (
    <div style={{ minHeight: "100vh", background: "#fafafa", color: "#0a0a0a" }}>
      <nav style={{ borderBottom: "1px solid #f0f0f0", padding: "0 48px", height: "56px", display: "flex", alignItems: "center", justifyContent: "space-between", background: "#fff" }}>
        <Link href="/" style={{ fontWeight: 800, fontSize: "15px", color: "#0a0a0a", textDecoration: "none", letterSpacing: "-0.04em" }}>m-ops</Link>
        <Link href="/terms" style={{ fontSize: "13px", color: "#888", textDecoration: "none" }}>Terms of Service</Link>
      </nav>
      <div style={{ maxWidth: "720px", margin: "0 auto", padding: "64px 48px" }}>
        <p style={{ fontSize: "11px", color: "#aaa", fontWeight: 600, letterSpacing: "0.1em", marginBottom: "12px" }}>LEGAL</p>
        <h1 style={{ fontSize: "36px", fontWeight: 800, letterSpacing: "-0.04em", marginBottom: "8px" }}>Privacy Policy</h1>
        <p style={{ color: "#888", marginBottom: "48px", fontSize: "14px" }}>Last updated: August 10, 2026</p>

        {[
          {
            title: "1. Information We Collect",
            body: "We collect information you provide directly (name, email, password), information from third-party sign-in providers (GitHub profile data), and usage data generated by your use of the Service (URLs you monitor, uptime results, timestamps).",
          },
          {
            title: "2. How We Use Your Information",
            body: "We use your data to: provide and improve the Service; send transactional emails (alerts, password resets); send product updates if you opt in; process payments; comply with legal obligations. We do not sell your personal data.",
          },
          {
            title: "3. Data Storage",
            body: "Your data is stored in a SQLite database hosted on our infrastructure. We take reasonable technical and organizational measures to protect your data. In production, data is encrypted at rest and in transit.",
          },
          {
            title: "4. Third-Party Services",
            body: "We use the following third-party services: GitHub (OAuth sign-in), Bachs (payment processing), Resend (transactional email). Each has its own privacy policy. We share only the data necessary for each service to function.",
          },
          {
            title: "5. Cookies",
            body: "We use a single session cookie (next-auth.session-token) to keep you signed in. We do not use advertising or tracking cookies.",
          },
          {
            title: "6. Data Retention",
            body: "We retain your data for as long as your account is active. When you delete your account, we delete your personal data within 30 days. Aggregated, anonymized data may be retained longer.",
          },
          {
            title: "7. Your Rights",
            body: "Depending on your jurisdiction, you may have the right to access, correct, or delete your personal data. You can update your profile and delete your account from Settings at any time. For other requests, contact us at privacy@m-ops.dev.",
          },
          {
            title: "8. Children",
            body: "The Service is not directed to children under 13. We do not knowingly collect data from children under 13.",
          },
          {
            title: "9. Changes to This Policy",
            body: "We may update this policy from time to time. We will notify you of material changes by email or via an in-app notice. Continued use after changes constitutes acceptance.",
          },
          {
            title: "10. Contact",
            body: "For privacy questions or requests, contact us at privacy@m-ops.dev.",
          },
        ].map(({ title, body }) => (
          <div key={title} style={{ marginBottom: "36px" }}>
            <h2 style={{ fontSize: "16px", fontWeight: 700, letterSpacing: "-0.02em", marginBottom: "10px" }}>{title}</h2>
            <p style={{ color: "#555", lineHeight: 1.8, fontSize: "14px", margin: 0 }}>{body}</p>
          </div>
        ))}
      </div>
      <footer style={{ borderTop: "1px solid #f0f0f0", padding: "28px 48px", display: "flex", gap: "24px", justifyContent: "center" }}>
        <Link href="/" style={{ color: "#888", fontSize: "13px", textDecoration: "none" }}>Home</Link>
        <Link href="/terms" style={{ color: "#888", fontSize: "13px", textDecoration: "none" }}>Terms of Service</Link>
        <a href="mailto:privacy@m-ops.dev" style={{ color: "#888", fontSize: "13px", textDecoration: "none" }}>Contact</a>
      </footer>
    </div>
  )
}
